### ISSUE TITLE
File handle leak

### ISSUE THREAD

**Issue by ghost** [pywharf/pywharf-core#7]
When I leave the server up overnight it fills up the filesystem /var/run which I'm using as the working directory.  The cause is twofold:
1) there doesn't seem to be any log rotation going on and the server emits a "pass" log message quite frequently
2) after awhile, stack traces are reported in the log file "OSError: [Errno 24] Too many open files"

I suspect some files might not be getting closed?  I haven't thoroughly reviewed the code to see if I can spot these.

From dramatic_worker.log:

> Traceback (most recent call last):
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/dramatiq/worker.py", line 470, in process_message
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/dramatiq/actor.py", line 145, in __call__
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/private_pypi_core/workflow.py", line 272, in sync_local_index_job
    wstat = build_workflow_stat(
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/private_pypi_core/workflow.py", line 122, in build_workflow_stat
    backend_instance_manager.load_pkg_repo_configs(pkg_repo_config_file)
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/private_pypi_core/backend.py", line 288, in load_pkg_repo_configs
  File "/usr/share/venv/pypi/lib/python3.8/site-packages/private_pypi_core/utils.py", line 25, in read_toml
    with open(path) as fin:
OSError: [Errno 24] Too many open files: '/etc/pypi/pypi.toml'

The repository specific log spits out similar stack traces.

Versions:
private-pypi        0.2.0
private-pypi-core   0.2.0
private-pypi-github 0.2.0

**Comment by huntzhan** [comment]
Thanks for the feedback. I'm looking into it.
All the explicit uses of file handles are guarded by the context manager (the `with xxx` statement), so I don't think that part was an issue. I'm looking into the implicit uses, i.e. the `logging.FileHandler`.
Have setup a server try to reproduce the situation.

**Comment by ghost** [comment]
This might be relevant...my systemd file contents:

> [Unit]
Description=Private PyPI Server
Requires=network-online.target
After=network-online.target

> [Service]
> Restart=on-success
> ExecStart=/bin/sh -c 'source /usr/share/venv/pypi/bin/activate && private_pypi server /var/run/pypi --config /etc/pypi/pypi.toml --admin_secret /etc/pypi/pypi-secret.toml --port 8888'

> [Install]
> WantedBy=multi-user.target

**Comment by huntzhan** [comment]
@jimrigsbee have a rollout in `pywharf==0.2.3` with the bugfix.

**Comment by huntzhan** [comment]
@jimrigsbee Could you help verify the fix?

**Comment by ghost** [comment]
Has it been packaged as private-pypiserver yet?  I've been installing under that package name.

**Comment by huntzhan** [comment]
Cannot do that (See https://github.com/pywharf/pywharf/issues/6).

**Comment by ghost** [comment]
Understood. I see the renamed package in the PyPI index now.  I'll try installing that.
